/*
 * Generated by TKLGEN - VersionFeb 20 2016
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef PLAYGROUNDMODULE_H
#define PLAYGROUNDMODULE_H


#include "Result.h"
#include "PlaygroundLang.h"

typedef enum 
{
  PrintNewLine,
  PrintPlus,
  PrintMinus,
  PrintMulti,
  PrintDiv,
  PrintPower,
  PrintLexeme,
  PrintNeg,
PlaygroundLang_OnError
}PlaygroundLang_Actions;

Result PlaygroundLang_Main(PlaygroundLang_Context* ctx);
const char* PlaygroundLang_Actions_Text(PlaygroundLang_Actions e);



#endif
