/*
 * Generated by TKLGEN - VersionNov  9 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef PLAYGROUNDMODULELEX_H
#define PLAYGROUNDMODULELEX_H

#include <wchar.h>
#include "sstream.h"


enum PlaygroundLang_Tokens
{
    TKPlus,
    TKMinus,
    TKMulti,
    TKDiv,
    TKPower,
    TKOpen,
    TKClose,
    TKEnd,
    TKEndMark,
    TKInteger,
    TKIdentifier,
    TKBlanks,
};

const wchar_t* PlaygroundLang_Tokens_ToString(enum PlaygroundLang_Tokens e);


int PlaygroundLang_NextTokenNoInterleave(struct sstream* stream,
  wchar_t** buffer,
  int* bufferSize,
 enum PlaygroundLang_Tokens* tk);

int PlaygroundLang_NextToken(struct sstream* stream,
   wchar_t** buffer,
   int* bufferSize,
  enum PlaygroundLang_Tokens* tk);

#endif
