/*
 * Generated by TKLGEN - VersionNov 18 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef PLAYGROUNDMODULELEX_H
#define PLAYGROUNDMODULELEX_H



typedef enum 
{
    TKPlus,
    TKMinus,
    TKMulti,
    TKDiv,
    TKPower,
    TKOpen,
    TKClose,
    TKEnd,
    TKEndMark,
    TKInteger,
    TKIdentifier,
    TKBlanks,
} PlaygroundLang_Tokens;

const char* PlaygroundLang_Tokens_ToString(PlaygroundLang_Tokens e);


int PlaygroundLang_GetNext(int state, wchar_t ch);
int PlaygroundLang_GetTokenFromState(int state, PlaygroundLang_Tokens* tk);
int PlaygroundLang_IsInterleave(PlaygroundLang_Tokens tk);

#endif
