/*
 * Generated by TKLGEN - VersionNov 18 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef PLAYGROUNDMODULE_H
#define PLAYGROUNDMODULE_H



#include "PlaygroundLang.h"
/*typedef enum 
{
  FIM,
  outro,
  Include,
  ifdef_begin,
  ifdef_end,
  elseif,
  ifndef,
  define,
  OnError
} PlaygroundLang_Actions;
*/
const char* PlaygroundLang_Actions_Text(PlaygroundLang_Actions e);


Result PlaygroundLang_Parse(PlaygroundLang_Context* ctx);



#endif
