/*
 * Generated by TKLGEN - VersionApr 24 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef EVAL_H
#define EVAL_H



enum Eval_Actions
{
  PrintAnd,
  PrintOr,
  PrintGreaterThan,
  PrintLessThan,
  PrintLessEqualThan,
  PrintGreaterEqualThan,
  PrintEquals,
  PrintNotEqual,
  PrintPlus,
  PrintMinus,
  PrintMulti,
  PrintDiv,
  PrintPower,
  PrintLexeme,
  PrintNeg,
};

typedef int (*Eval_OnAction)(enum Eval_Actions a, struct Eval_Context* ctx);

#define LEXEME_MAX 400

struct Eval_Context
{
    wchar_t lexeme[LEXEME_MAX];
    enum Eval_Tokens token;
    struct sstream* stream;
    void* pData;
    Eval_OnAction on_action;
};

int Eval_Parse(struct sstream* ss, Eval_OnAction action, void* context);



#endif
