/*
 * Generated by TKLGEN - VersionApr 24 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef EVALLEX_H
#define EVALLEX_H

#include <wchar.h>
#include "sstream.h"


enum Eval_Tokens
{
    TKIdentifier,
    TKPlus,
    TKMinus,
    TKMulti,
    TKDiv,
    TKPower,
    TKOpen,
    TKClose,
    TKEqual,
    TKGreaterThan,
    TKLessThan,
    TKGreaterEqualThan,
    TKLessEqualThan,
    TKDiferentThan,
    TKEnd,
    TKAnd,
    TKOr,
    TKEndMark,
    TKNumber,
    TKBlanks,
};

const wchar_t* Eval_Tokens_ToString(enum Eval_Tokens e);


int Eval_NextTokenNoInterleave(struct sstream* stream,
  wchar_t* buffer,
  int bufferSize,
 enum Eval_Tokens* tk);

int Eval_NextToken(struct sstream* stream,
   wchar_t* buffer,
   int bufferSize,
  enum Eval_Tokens* tk);

#endif
