/*
 * Generated by TKLGEN - VersionOct 27 2014
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef MODULESAMPLE2LEX_H
#define MODULESAMPLE2LEX_H

#include <wchar.h>
#include "sstream.h"


enum LanguageSample2_Tokens
{
    TKPlus,
    TKMinus,
    TKMulti,
    TKDiv,
    TKPower,
    TKOpen,
    TKClose,
    TKEqual,
    TKGreaterThan,
    TKLessThan,
    TKGreaterEqualThan,
    TKLessEqualThan,
    TKEnd,
    TKAnd,
    TKOr,
    TKEndMark,
    TKInteger,
    TKIdentifier,
    TKBlanks,
};

const wchar_t* LanguageSample2_Tokens_ToString(enum LanguageSample2_Tokens e);


int LanguageSample2_NextTokenNoInterleave(struct sstream* stream,
  wchar_t* buffer,
  int bufferSize,
 enum LanguageSample2_Tokens* tk);

int LanguageSample2_NextToken(struct sstream* stream,
   wchar_t* buffer,
   int bufferSize,
  enum LanguageSample2_Tokens* tk);

#endif
